---
title: "Fabre Museum Project: Statistical Analysis"
author: "Amélie Goubé"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggpubr)
```

```{r}
# Importing the cleaned file from Python
df <- read.csv("data/data_clean.csv", sep = ";")
# Quick chek
str(df)
```

```{r normality-all}
# 1. List of all variables to test (excluding 'sex')
vars <- c("number_of_zones_explored", "distance_travelled", "movement_autonomy", 
          "orientation_towards_artwork", "postural_adjustment", "physical_approach", 
          "overall_motor_engagement", "interaction_with_environment", 
          "interaction_with_peers", "interaction_with_adults")

# 2. Shapiro-Wilk Tests (Manual list for clarity in your report)
# We use na.omit() to ignore empty cells
shapiro.test(na.omit(df$number_of_zones_explored))
shapiro.test(na.omit(df$movement_autonomy))
shapiro.test(na.omit(df$orientation_towards_artwork))
shapiro.test(na.omit(df$postural_adjustment))
shapiro.test(na.omit(df$physical_approach))
shapiro.test(na.omit(df$overall_motor_engagement))
shapiro.test(na.omit(df$interaction_with_environment))
shapiro.test(na.omit(df$interaction_with_peers))
shapiro.test(na.omit(df$interaction_with_adults))

```

```{r}
### 1. Spatial Exploration: Number of Zones
ggboxplot(df, x = "sex", y = "number_of_zones_explored",
          fill = "sex", palette = "jco", add = "jitter",
          title = "Spatial Exploration by Gender",
          ylab = "Zones Explored") +
  stat_compare_means(method = "wilcox.test")
```
```{r}
### 2. Postural Adjustment
ggboxplot(df, x = "sex", y = "postural_adjustment",
          fill = "sex", palette = "jco", add = "jitter",
          title = "Postural Adjustment by Gender") +
  stat_compare_means(method = "wilcox.test")

### 3. Orientation towards Artwork
ggboxplot(df, x = "sex", y = "orientation_towards_artwork",
          fill = "sex", palette = "jco", add = "jitter",
          title = "Body Orientation by Gender") +
  stat_compare_means(method = "wilcox.test")
```

```{r}
### 4. Interaction with Adults
ggboxplot(df, x = "sex", y = "interaction_with_adults",
          fill = "sex", palette = "jco", add = "jitter",
          title = "Social Interaction (Adults) by Gender") +
  stat_compare_means(method = "wilcox.test")
```

